### ISSUE TITLE
sqlite creation / deletion code is wonky

### ISSUE THREAD

**Issue by tweibley** [jeremycole/mysql_cache_manager#4]
In my testing it looks like there is a problem creating the schema, and of course removal fails since it's not even there.

For example with --save you get something like this:

```
/usr/local/lib/ruby/gems/1.8/gems/sqlite3-ruby-1.3.0/lib/sqlite3/database.rb:83:in `initialize': no such table: metadata (SQLite3::SQLException)
from /usr/local/lib/ruby/gems/1.8/gems/sqlite3-ruby-1.3.0/lib/sqlite3/database.rb:83:in `new'
from /usr/local/lib/ruby/gems/1.8/gems/sqlite3-ruby-1.3.0/lib/sqlite3/database.rb:83:in `prepare'
from /usr/local/lib/ruby/gems/1.8/gems/sqlite3-ruby-1.3.0/lib/sqlite3/database.rb:257:in `query'
from /usr/local/lib/ruby/gems/1.8/gems/mysql_cache_manager-0.2.5/lib/mysql_cache_manager/cache_image/sqlite3.rb:44:in `empty!'
from /usr/local/lib/ruby/gems/1.8/gems/mysql_cache_manager-0.2.5/lib/mysql_cache_manager/cache_manager.rb:43:in `save_cache'
from /usr/local/lib/ruby/gems/1.8/gems/mysql_cache_manager-0.2.5/lib/mysql_cache_manager/cache_manager.rb:29:in `track_timing'
from /usr/local/lib/ruby/gems/1.8/gems/mysql_cache_manager-0.2.5/lib/mysql_cache_manager/cache_manager.rb:41:in `save_cache'
from /usr/local/lib/ruby/gems/1.8/gems/mysql_cache_manager-0.2.5/bin/mysql_cache_manager:126:in `save'
from /usr/local/lib/ruby/gems/1.8/gems/mysql_cache_manager-0.2.5/bin/mysql_cache_manager:205
from /usr/local/bin/mysql_cache_manager:19:in `load'
from /usr/local/bin/mysql_cache_manager:19
```

**Comment by jeremycole** [comment]
Hm, it works for me locally. This could happen if the SQLite file you pointed it at already existed (maybe a failed previous run?), though, since initialize would succeed but empty! would issue DELETEs on non-existent tables. I should probably check for the existence of the tables (and perhaps that their schema matches what's expected) when opening an existing SQLite file.
